class ProviderModel {
  final String id;
  final String name;
  final String phone;
  final String city;
  final String serviceType;
  final String? serviceTypeUrdu;
  final double rating;
  final double pricePerHour;
  final double distanceKm;
  final bool isVerified;
  final String rank;
  final String? profileImageUrl;
  final double lat;
  final double lng;
  final double totalEarnings;
  final int totalOrders;

  const ProviderModel({
    required this.id,
    required this.name,
    required this.phone,
    required this.city,
    required this.serviceType,
    this.serviceTypeUrdu,
    required this.rating,
    required this.pricePerHour,
    required this.distanceKm,
    this.isVerified = false,
    this.rank = 'Bronze',
    this.profileImageUrl,
    required this.lat,
    required this.lng,
    this.totalEarnings = 0,
    this.totalOrders = 0,
  });

  Map<String, dynamic> toMap() => {
    'id': id,
    'name': name,
    'phone': phone,
    'city': city,
    'serviceType': serviceType,
    'serviceTypeUrdu': serviceTypeUrdu,
    'rating': rating,
    'pricePerHour': pricePerHour,
    'distanceKm': distanceKm,
    'isVerified': isVerified,
    'rank': rank,
    'profileImageUrl': profileImageUrl,
    'lat': lat,
    'lng': lng,
    'totalEarnings': totalEarnings,
    'totalOrders': totalOrders,
  };

  factory ProviderModel.fromMap(Map<String, dynamic> map) => ProviderModel(
    id: map['id'] ?? '',
    name: map['name'] ?? '',
    phone: map['phone'] ?? '',
    city: map['city'] ?? '',
    serviceType: map['serviceType'] ?? '',
    serviceTypeUrdu: map['serviceTypeUrdu'],
    rating: (map['rating'] ?? 0.0).toDouble(),
    pricePerHour: (map['pricePerHour'] ?? 0.0).toDouble(),
    distanceKm: (map['distanceKm'] ?? 0.0).toDouble(),
    isVerified: map['isVerified'] ?? false,
    rank: map['rank'] ?? 'Bronze',
    profileImageUrl: map['profileImageUrl'],
    lat: (map['lat'] ?? 0.0).toDouble(),
    lng: (map['lng'] ?? 0.0).toDouble(),
    totalEarnings: (map['totalEarnings'] ?? 0.0).toDouble(),
    totalOrders: map['totalOrders'] ?? 0,
  );
}

// Mock data
final List<ProviderModel> mockProviders = [
  ProviderModel(
    id: 'p1',
    name: 'Muhammad Ali',
    phone: '03001234567',
    city: 'Karachi',
    serviceType: 'Plumber',
    serviceTypeUrdu: 'پلمبر',
    rating: 4.8,
    pricePerHour: 800,
    distanceKm: 1.2,
    isVerified: true,
    rank: 'Gold',
    profileImageUrl: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150',
    lat: 24.8607,
    lng: 67.0011,
    totalEarnings: 145000,
    totalOrders: 187,
  ),
  ProviderModel(
    id: 'p2',
    name: 'Asif Khan',
    phone: '03111234567',
    city: 'Karachi',
    serviceType: 'Electrician',
    serviceTypeUrdu: 'الیکٹریشن',
    rating: 4.5,
    pricePerHour: 900,
    distanceKm: 2.1,
    isVerified: true,
    rank: 'Silver',
    profileImageUrl: 'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=150',
    lat: 24.8700,
    lng: 67.0200,
    totalEarnings: 98000,
    totalOrders: 122,
  ),
  ProviderModel(
    id: 'p3',
    name: 'Rashid Mehmood',
    phone: '03211234567',
    city: 'Lahore',
    serviceType: 'AC Repair',
    serviceTypeUrdu: 'اے سی مرمت',
    rating: 4.9,
    pricePerHour: 1200,
    distanceKm: 0.8,
    isVerified: true,
    rank: 'Gold',
    profileImageUrl: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=150',
    lat: 31.5204,
    lng: 74.3587,
    totalEarnings: 210000,
    totalOrders: 245,
  ),
  ProviderModel(
    id: 'p4',
    name: 'Tariq Hussain',
    phone: '03311234567',
    city: 'Islamabad',
    serviceType: 'Cleaner',
    serviceTypeUrdu: 'صفائی',
    rating: 4.3,
    pricePerHour: 600,
    distanceKm: 3.5,
    isVerified: false,
    rank: 'Bronze',
    profileImageUrl: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=150',
    lat: 33.7294,
    lng: 73.0931,
    totalEarnings: 45000,
    totalOrders: 56,
  ),
  ProviderModel(
    id: 'p5',
    name: 'Imran Shah',
    phone: '03451234567',
    city: 'Karachi',
    serviceType: 'Car Repair',
    serviceTypeUrdu: 'گاڑی مرمت',
    rating: 4.7,
    pricePerHour: 1500,
    distanceKm: 1.9,
    isVerified: true,
    rank: 'Silver',
    profileImageUrl: 'https://images.pexels.com/photos/1040880/pexels-photo-1040880.jpeg?auto=compress&cs=tinysrgb&w=150',
    lat: 24.8550,
    lng: 67.0150,
    totalEarnings: 132000,
    totalOrders: 98,
  ),
  ProviderModel(
    id: 'p6',
    name: 'Zubair Ahmed',
    phone: '03561234567',
    city: 'Lahore',
    serviceType: 'Tutor',
    serviceTypeUrdu: 'ٹیوٹر',
    rating: 4.6,
    pricePerHour: 700,
    distanceKm: 2.8,
    isVerified: true,
    rank: 'Silver',
    profileImageUrl: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=150',
    lat: 31.5350,
    lng: 74.3700,
    totalEarnings: 76000,
    totalOrders: 134,
  ),
  ProviderModel(
    id: 'p7',
    name: 'Hamid Raza',
    phone: '03129876543',
    city: 'Islamabad',
    serviceType: 'Plumber',
    serviceTypeUrdu: 'پلمبر',
    rating: 4.4,
    pricePerHour: 750,
    distanceKm: 1.5,
    isVerified: true,
    rank: 'Silver',
    profileImageUrl: null,
    lat: 33.7200,
    lng: 73.1000,
    totalEarnings: 88000,
    totalOrders: 110,
  ),
  ProviderModel(
    id: 'p8',
    name: 'Fahad Iqbal',
    phone: '03335551234',
    city: 'Karachi',
    serviceType: 'Driver',
    serviceTypeUrdu: 'ڈرائیور',
    rating: 4.9,
    pricePerHour: 1000,
    distanceKm: 0.5,
    isVerified: true,
    rank: 'Gold',
    profileImageUrl: null,
    lat: 24.8620,
    lng: 67.0050,
    totalEarnings: 190000,
    totalOrders: 300,
  ),
];
